fixtures:
  repositories:
    concat: 'git://github.com/ripienaar/puppet-concat.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    sudo: 'https://github.com/saz/puppet-sudo'

  symlinks:
    icinga: "#{source_dir}"

